import { test, expect } from '@playwright/test'

for (const locale of ['', 'en/']) {
  test(`${locale || 'zh/'} createStyles examples are interactive`, async ({ page }, info) => {
    const errors: string[] = []
    page.on('pageerror', error => errors.push(error.message))
    await page.goto(`/antdv-style/${locale}guide/create-styles`)
    await expect(page.getByTestId('static-example')).toHaveCSS('padding-top', '20px')
    const tokens = page.locator('[data-example="tokens"]')
    const before = await page.getByTestId('token-normal').evaluate(el => getComputedStyle(el).backgroundColor)
    await tokens.getByRole('checkbox').check()
    await expect(page.getByTestId('token-normal')).not.toHaveCSS('background-color', before)
    const select = page.getByTestId('props-select')
    await select.getByRole('combobox').click()
    await expect(select).toHaveCSS('outline-color', 'rgb(82, 196, 26)')
    await page.locator('.ant-select-item-option').filter({ hasText: 'Option 1' }).click()
    await expect(select).toHaveCSS('background-color', 'rgb(230, 244, 255)')
    const command = page.locator('[data-example="command"]')
    await command.getByRole('searchbox').fill('Color')
    await expect(command.getByRole('button')).toHaveCount(1)
    await command.getByRole('button').click()
    await expect(command.getByRole('button')).toHaveAttribute('aria-pressed', 'true')
    const animation = page.getByTestId('keyframes-helper')
    await page.locator('[data-example="keyframes"]').scrollIntoViewIfNeeded()
    await expect(animation).not.toHaveCSS('animation-name', 'none')
    const first = await animation.evaluate(el => getComputedStyle(el).transform)
    await expect.poll(() => animation.evaluate(el => getComputedStyle(el).transform)).not.toBe(first)
    await page.locator('[data-example="keyframes"]').getByRole('checkbox').check()
    await expect(animation).toHaveCSS('animation-play-state', 'paused')
    await expect(page.getByTestId('keyframes-native')).not.toHaveCSS('animation-name', 'none')
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    expect(errors).toEqual([])
    await page.screenshot({ path: info.outputPath('create-styles.png'), animations: 'disabled' })
  })

  test(`${locale || 'zh/'} migration comparison reacts to theme and props`, async ({ page }, info) => {
    await page.goto(`/antdv-style/${locale}guide/migrate-less-component`)
    const example = page.locator('[data-example="migration"]')
    const after = page.getByTestId('migration-horizontal')
    const oldBackground = await after.evaluate(el => getComputedStyle(el).backgroundColor)
    await example.getByRole('checkbox').check()
    await expect(after).not.toHaveCSS('background-color', oldBackground)
    await expect(page.locator('.migration-before').first()).toHaveCSS('background-color', 'rgb(255, 255, 255)')
    await example.getByRole('spinbutton').fill('42')
    await expect(after).toContainText('42')
    await expect(page.getByTestId('migration-vertical')).toHaveCSS('flex-direction', 'column')
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: info.outputPath('migration.png'), animations: 'disabled' })
  })

  test(`${locale || 'zh/'} instance collection and global cleanup`, async ({ page }) => {
    await page.goto(`/antdv-style/${locale}api/create-instance`)
    await expect(page.getByTestId('instance-static')).toHaveCSS('padding-top', '12px')
    expect(await page.locator('[data-example="instance"] [data-testid="instance-style-container"] style').count()).toBeGreaterThan(0)
    await page.locator('[data-example="instance"]').getByRole('button', { name: 'Collect CSS' }).click()
    await expect(page.getByTestId('collected-css')).toContainText('docs-capability')
    await page.goto(`/antdv-style/${locale}api/global-styles`)
    await expect(page.locator('[data-global-target]')).toHaveCSS('color', 'rgb(22, 119, 255)')
    await page.getByRole('button', { name: 'Collect CSS' }).click()
    await expect(page.getByTestId('collected-css')).toContainText('data-global-target')
    await page.getByLabel('Mounted', { exact: true }).uncheck()
    await expect(page.locator('[data-global-target]')).toHaveCount(0)
    await page.getByRole('button', { name: 'Collect CSS' }).click()
    await expect(page.getByTestId('collected-css')).not.toContainText('data-global-target')
  })

  test(`${locale || 'zh/'} custom appearance, controlled mode and responsive configuration`, async ({ page }) => {
    await page.goto(`/antdv-style/${locale}guide/custom-theme`)
    await page.getByRole('radio', { name: 'grey', exact: true }).check()
    await expect(page.getByTestId('appearance-output')).toHaveText('grey')
    await page.goto(`/antdv-style/${locale}guide/switch-theme`)
    const example = page.locator('[data-example="controlled"]')
    await example.getByRole('button', { name: 'dark', exact: true }).click()
    await expect(example.getByTestId('appearance-output')).toHaveText('dark')
    await example.getByRole('checkbox').uncheck()
    await example.getByRole('button', { name: 'light', exact: true }).click()
    await expect(example.getByTestId('requested-mode')).toHaveText('light')
    await expect(example.getByTestId('appearance-output')).toHaveText('dark')
    await page.goto(`/antdv-style/${locale}api/use-responsive`)
    const range = page.locator('[data-example="responsive"]').getByRole('slider')
    await range.focus()
    await range.press('End')
    await expect(page.getByTestId('custom-md')).toHaveText('md: false')
    await range.press('Home')
    await expect(page.getByTestId('custom-md')).toHaveText(`md: ${page.viewportSize()!.width >= 600}`)
  })

  test(`${locale || 'zh/'} overrides, responsive styles and dynamic list`, async ({ page }, info) => {
    const errors: string[] = []
    page.on('pageerror', error => errors.push(error.message))
    await page.goto(`/antdv-style/${locale}best-practice/antd-override`)
    const example = page.locator('[data-example="overrides"]')
    const button = page.getByTestId('specificity-button')
    await expect(button).toHaveCSS('border-left-width', '1px')
    await example.getByRole('checkbox').check()
    await expect(button).toHaveCSS('border-left-width', '3px')
    const input = example.getByRole('textbox')
    await input.fill('42')
    await expect(input).toHaveValue('42')
    await expect(example.locator('.ant-input-affix-wrapper')).toHaveCSS('border-left-width', '2px')
    await page.goto(`/antdv-style/${locale}api/create-styles`)
    const responsive = page.getByTestId('responsive-styles')
    await expect(responsive).toHaveText(page.viewportSize()!.width < 576 ? 'mobile' : 'laptop')
    await expect(responsive).toHaveCSS('background-color',
      page.viewportSize()!.width < 576 ? 'rgb(255, 251, 230)' : 'rgb(230, 244, 255)')
    await page.goto(`/antdv-style/${locale}api/create-static-styles`)
    const staticBanner = page.getByText('Generated once, reused by every component instance.', { exact: true })
    await expect(staticBanner).toHaveCSS('background-color', 'rgb(22, 119, 255)')
    await expect(page.getByTestId('responsive-styles')).toHaveCSS('background-color',
      page.viewportSize()!.width < 480 ? 'rgb(255, 251, 230)' : 'rgb(255, 240, 246)')
    await page.goto(`/antdv-style/${locale}best-practice/performance`)
    const list = page.getByTestId('dynamic-list')
    await expect(list.locator('> div')).toHaveCount(100)
    await page.getByLabel('Padding', { exact: true }).focus()
    await page.getByLabel('Padding', { exact: true }).press('End')
    await expect(list.locator('> div').first()).toHaveCSS('padding-left', '48px')
    await page.getByLabel('Rows', { exact: true }).focus()
    await page.getByLabel('Rows', { exact: true }).press('End')
    await expect(list.locator('> div')).toHaveCount(1000)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    expect(errors).toEqual([])
    await page.screenshot({ path: info.outputPath('dynamic-list.png'), animations: 'disabled' })
  })

  test(`${locale || 'zh/'} App scopes native styles without changing provider-only text`, async ({ page }) => {
    await page.goto(`/antdv-style/${locale}api/theme-provider`)
    const example = page.locator('[data-example="composition"]')
    const bare = page.getByTestId('provider-only').getByTestId('composition-text')
    const wrapped = page.getByTestId('provider-app').getByTestId('composition-text')
    const baseline = await bare.evaluate(el => getComputedStyle(el).color)
    await expect(wrapped).toHaveCSS('color', 'rgb(196, 29, 127)')
    await example.getByRole('checkbox').check()
    await expect(bare).toHaveCSS('color', baseline)
    await expect(page.getByTestId('provider-app').locator('output')).toHaveText('dark')
    await expect(wrapped).toHaveCSS('color', 'rgb(196, 29, 127)')
  })
}
